spring:
  mail:
    host: smtp.163.com
    username: xxc20241192299468@163.com
    password: ENdLVjwAHqUWZGfe
  rabbitmq:
    addresses: 47.115.213.32
    username: admin
    password: admin
    virtual-host: /test
  security:
    jwt:
      key: my-secret-key
      expire: 7
  data:
    redis:
      host: 47.115.213.32
      port: 6379
  datasource:
    username: root
    password: baby520.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test